### ISSUE TITLE
Using Parsoid and VisualEditor

### ISSUE THREAD

**Issue by kostajh** [addshore/mediawiki-docker-dev#70]
I've tried a few things without success:

- Adding `thenets/parsoid` to the `docker-compose.yml` file
- Running `thenets/parsoid` as a separate container using `--network=host`
- Installing `parsoid` via `apt` in the `web` container (eww)

But in all cases I've run into issues with correctly setting and handling URLs and getting traffic to flow correctly between containers. If anyone has a working example, I'd love to see it.

**Comment by kostajh** [comment]
We should look at how wikimedia/mediawiki-containers has done this. It seems like the key is to use dnsdock https://github.com/wikimedia/mediawiki-containers/blob/master/docker-compose.yml#L57.

**Comment by NoumanSaleem** [comment]
This should be possible with compose v3 and by setting a link alias for web in parsoid

```
  parsoid:
    image: thenets/parsoid:0.8.1
    ports:
      - "8000:8000"
    environment:
      - PARSOID_DOMAIN_mediawiki=http://default.web.mw.localhost/mediawiki/api.php
      - PARSOID_LOGGING_LEVEL=debug
    links:
      - "web:default.web.mw.localhost"
```

full file:
```
version: '3'

services:
  parsoid:
    image: thenets/parsoid:0.8.1
    ports:
      - "8000:8000"
    environment:
      - PARSOID_DOMAIN_mediawiki=http://default.web.mw.localhost/mediawiki/api.php
      - PARSOID_LOGGING_LEVEL=debug
    links:
      - "web:default.web.mw.localhost"

  db-master:
    image: ${DB}:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - sql-data-master:/var/lib/mysql
      - ./config/mysql/master:/tmp/mwdd
    entrypoint: "/tmp/mwdd/entrypoint.sh"
    command: "mysqld"

  db-slave:
    image: ${DB}:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - sql-data-slave:/var/lib/mysql
      - ./config/mysql/slave:/tmp/mwdd
    entrypoint: "/tmp/mwdd/entrypoint.sh"
    command: "mysqld"

  db-configure:
    image: ${DB}:latest
    environment:
      - "MYSQL_SLAVE_PASSWORD=toor"
      - "MYSQL_MASTER_PASSWORD=toor"
      - "MYSQL_ROOT_PASSWORD=toor"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    depends_on:
     - db-master
     - db-slave
    volumes:
      - ./scripts/mysql_connector.sh:/tmp/mysql_connector.sh
      - ./scripts/wait-for-it.sh:/tmp/wait-for-it.sh
    command: /bin/bash -x /tmp/mysql_connector.sh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_USER:root
     - PMA_PASSWORD:toor
     - PMA_HOSTS=db-master,db-slave
     - PMA_ARBITRARY=1
     - VIRTUAL_HOST=phpmyadmin.mw.localhost
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  web:
    image: webdevops/${PHPORHHVM}-${WEBSERVER}${DOCKERPHPDEV}:${RUNTIMEVERSION}
    environment:
     - WEB_DOCUMENT_ROOT=/var/www
     # Used by various maintenance scripts to find MediaWiki.
     # Also required for /var/www/index.php - https://phabricator.wikimedia.org/T153882
     - MW_INSTALL_PATH=/var/www/mediawiki
     - VIRTUAL_HOST=*.web.mw.localhost
     - PHP_DEBUGGER=xdebug
     - XDEBUG_REMOTE_AUTOSTART=1
     - XDEBUG_REMOTE_HOST=${IDELOCALHOST}
     - XDEBUG_REMOTE_PORT=9000
     - XDEBUG_REMOTE_CONNECT_BACK=0
     - PHP_IDE_CONFIG=serverName=docker
    depends_on:
     - db-configure
    volumes:
     - "${DOCKER_MW_PATH}:/var/www/mediawiki"
     - ./config/mediawiki:/var/www/mediawiki/.docker:ro
     - ./config/hhvm/php.ini:/etc/hhvm/php.ini:ro
     - ./config/hhvm/server.ini:/etc/hhvm/server.ini:ro
     - ./scripts/wait-for-it.sh:/srv/wait-for-it.sh:ro
     - mw-images:/var/www/mediawiki/images/docker
  graphite-statsd:
    image: hopsoft/graphite-statsd
    environment:
     - VIRTUAL_HOST=graphite.mw.localhost
    volumes:
     - graphite-data:/opt/graphite/storage

  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
     - VIRTUAL_HOST=proxy.mw.localhost
    ports:
      - "${DOCKER_MW_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  sql-data-master:
  sql-data-slave:
  graphite-data:
  mw-images:
```
